services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8080:8080 # for jenkins web interface
      - 50000:50000 # for jenkins slave agents (runners)
    container_name: jenkins-tp01-I4c
    volumes:
      - "D:/I4/SERMISTER II/DevOps/TP/A/TP01/jenkins_home:/var/jenkins_home"
    links:
      - agent1
  agent1:
    build: ./laravel-agent
    image: i4c/jenkins-agent:latest
    container_name: jenkins-laravel-agent-I4c
    environment:
      
      - JENKINS_AGENT_SSH_PUBKEY=ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOm5ATQs5YNnPC+dB7IHQtKoQeDwwaa35wgdM702L/C4 U-ser@DESKTOP-JH8Q78A
    volumes:
    - "D:/I4/SERMISTER II/DevOps/TP/A/TP01/jenkins_home:/var/jenkins_home" # replace with the actual secret from Jenkins